services:
  app:
    image: mowoh/spark-demo:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
    volumes:
      - /app/data
#     depends_on:
#       - db
#
#   db:
#     image: postgres:13
#     environment:
#       POSTGRES_DB: spark_demo
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#     volumes:
#       - db-data:/var/lib/postgresql/data
#
# volumes:
#   app-data:
#   db-data: