apiVersion: v1
kind: Service
metadata:
  name: spark-demo-service
  labels:
    app: spark-demo
spec:
  selector:
    app: spark-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
# apiVersion: v1
# kind: Service
# metadata:
#   name: spark-demo-service
#   labels:
#     app: spark-demo
# spec:
#   selector:
#     app: spark-demo
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8080
#   type: ClusterIP